//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Stats.Repository
{
    using System;
    using System.Collections.Generic;
    using F1Stats.Data;

    public class DbInit
    {
        public F1StatsDbContext db { get; set; }
        public DbInit()
        {
            this.db = new F1StatsDbContext();
        }
    }
}
